### PR TITLE
add changes required for successful Vivado 2017.4 synthesis (nv_small only)

### PR DESCRIPTION
**Pull request by mmaciag**
This pull was submitted at the @jwise request, see #110.

**What has changed:**
- modify each `reg`/`wire` keyword where Vivado 2017.4 claimed incorrect assignment
- add missing `nv_ram_rwsp_8x65.v` to small_rams

**What has been tested:**
- manual import .v/.vh files required to elaborate top module *NV_nvdla.v*
- elaboration completes successfully
- synthesis completes successfully

**What has not been tested:**
- other models than *nv_small*

**Other notes:**
I recall that at least one wire/reg was dependent on selected .spec (tied to either comb or sequential output). Therefore I strongly recommend this modification to be reviewed against specs other than *nv_small*.

### CODE REVIEW

**Comment by mmaciag** [comment]
Ok, Hope it's not a problem if it take few working days.

**Comment by mmaciag** [comment]
@jwise FYI CLA has been mailed.

**Comment by skmp** [comment]
@mmaciag the CLAs have to go through physical paper?

**Comment by mmaciag** [comment]
@skmp why? I just followed http://nvdla.org/contributing.html

> To sign the CLA, please download it, print it out, sign it, scan it, and send it to us at nvdla@nvidia.com. We only need one CLA per organization, [...]

**Comment by skmp** [comment]
Ahh, I see. Makes sense. Still sad there is no CLA bot like in other projects. https://cla-assistant.io Is pretty nice.

**Comment by jwise** [comment]
Thanks! I hope to get to merge this tomorrow.

@skmp - Yeah, we have been considering this too. For now, we really want to have a signed version, since "employer owns your work" clauses are very common in the US. A CLA bot to assist with the mechanics is definitely on the to do list, though.

**Comment by jwise** [comment]
Merged.  Thanks again!  I've also pushed a few other odds-and-ends updates.

**Comment by peterzh2018888** [comment]
did you try to create the IP for the nv_small with Vivado? If so, how did you manage the connections with the Zynq UltraScale+?

**Comment by peterzh2018888** [comment]
did you try to create the IP for the nv_small with Vivado? If so, how did you manage the connections with the Zynq UltraScale+?

**Pull request merged**
